#!/bin/python3
from turtle import *
from random import randint
speed(10)
penup()
goto(-140,140)
penup()
for step in range(8):
  write(step,align='center')
  right(90)
  forward(10)
  pendown()
  forward(20)
  penup()
  forward(20)
  pendown()
  forward(20)
  penup()
  forward(20)
  pendown()
  forward(20)
  penup()
  forward(20)
  pendown()
  forward(20)
  penup()
  forward(10)
  pendown()
  penup()
  backward(160)
  left(90)
  forward(20)
ada=Turtle()
ada.color('red')
ada.shape('turtle')
ada.penup()
ada.goto(-160,100)
ada.pendown()

bob=Turtle()
bob.color('blue')
bob.shape('turtle')
bob.penup()
bob.goto(-160,70)
bob.pendown()

sop=Turtle()
sop.color('green')
sop.shape('turtle')
sop.penup()
sop.goto(-160,40)
sop.pendown()

dop=Turtle()
dop.color('yellow')
dop.shape('turtle')
dop.penup()
dop.penup()
dop.goto(-160,10)
dop.pendown()

for turn in range(100):
  ada.forward(randint(1,3))
  bob.forward(randint(1,3))
  sop.forward(randint(1,3))
  dop.forward(randint(1,3))
